# Generated by Django 4.1.5 on 2023-01-05 08:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('flow_volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(null=True)),
                ('flow_volume', models.FloatField()),
                ('total_spent', models.FloatField(default=0)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='dispenser.dispenser')),
            ],
        ),
    ]
